PREFIX dcterms: <http://purl.org/dc/terms/> 
PREFIX rdfs: <http://www.w3schools.com/RDF/rdf-schema.xml>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX my: <http://my/>

CONSTRUCT {
    my:property my:id {{ property }} .
    my:property my:relation my:subject .
    my:property my:count ?count .
    my:property my:label ?label .
    my:property my:data ?object .
    ?object ?property ?value .
}

WHERE {
    {
        SELECT ?object
        WHERE { {{ resource }} {{ property }} ?object . }
        LIMIT {{ limit | default:10 }}
        OFFSET {{ offset | default:0 }}
    }
    {
        SELECT (COUNT(DISTINCT ?dist) as ?count)
        WHERE { {{ resource }} {{ property }} ?dist . }
    }
    {
        VALUES ?property { {{ requested-properties | escape-uri-list }} } .
        ?object ?property ?value .
    }
    UNION
    {
        {{ property }} rdfs:label ?label .
    }
    UNION
    {
        {{ resource }} {{ property }} [] .
    }
}