PREFIX my: <http://my/>

CONSTRUCT {
    {{ property }} my:relation my:object .
    {{ property }} my:graph ?graph .
    {{ property }} my:count ?count .
    {{ property }} my:label ?label .
    {{ property }} my:data ?object .
    ?object ?property ?value .
}

WHERE {
    {
        SELECT ?object
        WHERE { ?object {{ property }} {{ resource }} . }
        LIMIT {{ limit | default:10 }}
        OFFSET {{ offset | default:0 }}
    }
    {
        SELECT (COUNT(?object) as ?count)
        WHERE { ?object {{ property }} {{ resource }} . }
    }
    GRAPH ?graph { ?object {{ property }}  {{ resource }} }
    OPTIONAL {
        VALUES ?property { {{ requested-properties | escape-uri-list }} } .
        ?object ?property ?value .
    }
    OPTIONAL {
        {{ property }} rdfs:label ?label .
    }
}