PREFIX my: <http://my/>
PREFIX res: {{ resource }}

CONSTRUCT {
    res: a ?type .
    res: my:subject ?out .
    res: my:object ?in
}

WHERE {
    OPTIONAL { res: a ?type }
    OPTIONAL {
        SELECT DISTINCT  ?out
        WHERE {
            res: ?out [] .
            FILTER(?out NOT IN (rdf:type))
        }
    }
    OPTIONAL {
        SELECT DISTINCT  ?in
        WHERE {
            OPTIONAL { [] ?in res: }
        }
    }
}