PREFIX my: <http://my/>

CONSTRUCT {
    my:out {{ property }} ?object .
    ?object ?property ?value .
}

WHERE {
    {
        SELECT ?object
        WHERE { {{ resource }} {{ property }} ?object . }
        LIMIT {{ limit | default:10 }}
        OFFSET {{ offset | default:0 }}
    }
    OPTIONAL {
        VALUES ?property { {{ requested-properties | escape-uri-list }} } .
        ?object ?property ?value .
    }
}